// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kovusvmvsjguukhiyjdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdnVzdm12c2pndXVraGl5amR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjQyNzMsImV4cCI6MjA1NzYwMDI3M30.0ja3QcX1veDf8e2k1uuCmyza5zv1lsP5Kh94U7qFiSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);